### ISSUE TITLE
api似乎出了问题

### ISSUE THREAD

**Issue by BiDuang** [RimoChan/Mask-Translator#2]
报错如下:
`
INFO:root:上網查找「类」
Traceback (most recent call last):
  File "/root/Mask-Translator/mask_change.py", line 56, in <module>
    fire.Fire(go)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/Mask-Translator/mask_change.py", line 36, in go
    結果 = 翻譯.處理(f.read())
  File "/root/Mask-Translator/翻譯.py", line 75, in 處理
    組[1] = 單詞替換(x)
  File "/root/Mask-Translator/翻譯.py", line 50, in 單詞替換
    結果 = 翻譯(cc.convert(單詞))
  File "/root/Mask-Translator/翻譯.py", line 31, in 翻譯
    return 改變形態(詞義.解釋(單詞))
  File "/root/Mask-Translator/詞義.py", line 49, in 解釋
    raise Exception(f'上網的回應爲「{text}」')
Exception: 上網的回應爲「﻿"TranslateApiException: AppId is over the quota : ID=V2_Json_Translate.HKGE.627E.0523T0244.486828F"」
`

**所以是不是api出了问题捏**

**Comment by BiDuang** [comment]
运行环境为服务器下的Ubuntu
